// Salva-Digital-Tech/packages/backend/src/models/ReservedNames.js
// This model is NOT a Mongoose schema — it is a hardcoded lookup set.
// All names are stored lowercase. The lookup is O(1) via Set.

const RESERVED_NAMES_LIST = [
  // ── Ethereum / Core Web3 ─────────────────────────────────────────────────
  'vitalik',
  'buterin',
  'vitalikbuterin',
  'vitalik.buterin',
  'buterin.vitalik',
  'gavin',
  'wood',
  'gavinwood',
  'gavin.wood',
  'wood.gavin',
  'silvio',
  'micali',
  'silviomicali',
  'silvio.micali',
  'micali.silvio',
  'hoskinson',
  'charleshoskinson',
  'charles.hoskinson',
  'hoskinson.charles',
  'anatoly',
  'yakovenko',
  'anatolyyakovenko',
  'anatoly.yakovenko',
  'yakovenko.anatoly',
  'ryan',
  'selkis',
  'ryanselkis',
  'ryan.selkis',
  'selkis.ryan',
  'balaji',
  'srinivasan',
  'balajisrinivasan',
  'balaji.srinivasan',
  'srinivasan.balaji',
  'nick',
  'szabo',
  'nickszabo',
  'nick.szabo',
  'szabo.nick',
  'adam',
  'back',
  'adamback',
  'adam.back',
  'back.adam',
  'hal',
  'finney',
  'halfinney',
  'hal.finney',
  'finney.hal',
  'satoshi',
  'nakamoto',
  'satoshinakamoto',
  'satoshi.nakamoto',
  'nakamoto.satoshi',
  'roger',
  'ver',
  'rogerver',
  'roger.ver',
  'ver.roger',
  'brian',
  'armstrong',
  'brianarmstrong',
  'brian.armstrong',
  'armstrong.brian',
  'sam',
  'bankman',
  'samfried',
  'sambankmanfried',
  'sam.bankman',
  'bankman.sam',
  'justin',
  'sun',
  'justinsun',
  'justin.sun',
  'sun.justin',
  'changpeng',
  'zhao',
  'cz',
  'changpengzhao',
  'changpeng.zhao',
  'zhao.changpeng',
  'do',
  'kwon',
  'dokwon',
  'do.kwon',
  'kwon.do',
  'stani',
  'kulechov',
  'stanikulechov',
  'stani.kulechov',
  'kulechov.stani',
  'andre',
  'cronje',
  'andrecronje',
  'andre.cronje',
  'cronje.andre',
  'hayden',
  'adams',
  'haydenbadams',
  'hayden.adams',
  'adams.hayden',
  'kain',
  'warwick',
  'kainwarwick',
  'kain.warwick',
  'warwick.kain',
  'robert',
  'leshner',
  'robertleshner',
  'robert.leshner',
  'leshner.robert',
  'rune',
  'christensen',
  'runechristensen',
  'rune.christensen',
  'christensen.rune',

  // ── Wallets ───────────────────────────────────────────────────────────────
  'metamask',
  'meta.mask',
  'mask.meta',
  'trustwallet',
  'trust.wallet',
  'wallet.trust',
  'coinbase',
  'coinbasewallet',
  'coinbase.wallet',
  'wallet.coinbase',
  'rainbow',
  'rainbowwallet',
  'rainbow.wallet',
  'phantom',
  'phantomwallet',
  'phantom.wallet',
  'ledger',
  'ledgerwallet',
  'ledger.wallet',
  'trezor',
  'trezorwallet',
  'trezor.wallet',
  'exodus',
  'exoduswallet',
  'exodus.wallet',
  'atomic',
  'atomicwallet',
  'atomic.wallet',
  'argent',
  'argentwallet',
  'argent.wallet',
  'zerion',
  'zerionwallet',
  'zerion.wallet',
  'safe',
  'gnosis',
  'gnosissafe',
  'gnosis.safe',
  'safe.gnosis',
  'rabby',
  'rabbywallet',
  'rabby.wallet',
  'frame',
  'framewallet',
  'frame.wallet',
  'backpack',
  'backpackwallet',
  'backpack.wallet',
  'okx',
  'okxwallet',
  'okx.wallet',
  'bybit',
  'bybitwallet',
  'bybit.wallet',
  'kraken',
  'krakenwallet',
  'kraken.wallet',
  'binancewallet',
  'binance.wallet',

  // ── Exchanges ─────────────────────────────────────────────────────────────
  'ftx',
  'gemini',
  'kucoin',
  'huobi',
  'gateio',
  'bitfinex',
  'bitstamp',
  'poloniex',
  'bithumb',
  'bitget',
  'mexc',
  'lbank',
  'bitmart',
  'probit',

  // ── DeFi Infrastructure ───────────────────────────────────────────────────
  'lido',
  'lidofinance',
  'lido.finance',
  'finance.lido',
  'rocketpool',
  'rocket.pool',
  'pool.rocket',
  'frax',
  'fraxfinance',
  'frax.finance',
  'convex',
  'convexfinance',
  'convex.finance',
  'pendle',
  'pendlefinance',
  'pendle.finance',
  'eigenlayer',
  'eigen.layer',
  'layer.eigen',
  'ether',
  'etherfi',
  'ether.fi',
  'fi.ether',
  'jito',
  'jitonetwork',
  'jito.network',
  'marinade',
  'marinadefinance',
  'marinade.finance',
  'olympus',
  'ohm',
  'klima',
  'klimadao',
  'klima.dao',
  'sperax',
  'bluechip',
  'reserve',
  'reflexer',

  // ── NFT / Gaming ──────────────────────────────────────────────────────────
  'bayc',
  'mayc',
  'cryptopunks',
  'crypto.punks',
  'azuki',
  'doodles',
  'moonbirds',
  'clonex',
  'sandbox',
  'decentraland',
  'axie',
  'axieinfinity',
  'axie.infinity',
  'stepn',
  'sorare',
  'gods',
  'godenchained',
  'gods.unchained',
  'illuvium',
  'gala',
  'immutable',
  'imx',
  'enjin',
  'enj',
  'superrare',
  'knownorigin',

  // ── Infrastructure / Dev ──────────────────────────────────────────────────
  'infura',
  'alchemy',
  'morales',
  'quicknode',
  'ankr',
  'the.graph',
  'thegraph',
  'graph',
  'subgraph',
  'hardhat',
  'foundry',
  'truffle',
  'brownie',
  'openzeppelin',
  'open.zeppelin',
  'zeppelin',
  'ethers',
  'web3js',
  'web3.js',
  'viem',
  'wagmi',
  'walletconnect',
  'wallet.connect',
  'connect.wallet',
  'wormhole',
  'layerzero',
  'layer.zero',
  'axelar',
  'multichain',
  'multi.chain',
  'across',
  'hop',
  'stargate',
  'stargateprotocol',
  'stargate.protocol',
  'socket',
  'celer',
  'celernetwork',
  'celer.network',

  // ── DAOs / Governance ─────────────────────────────────────────────────────
  'uniswap.dao',
  'aave.dao',
  'compound.dao',
  'maker.dao',
  'makerdao',
  'gitcoin',
  'git.coin',
  'bankless',
  'bank.less',
  'banklessdao',
  'bankless.dao',
  'pleasrdao',
  'pleasr.dao',
  'constitutionaldao',
  'constitution.dao',
  'flamincome',
  'indexcoop',
  'index.coop',
  'rabbithole',
  'rabbit.hole',
  'layer3',
  'layer.3',
  'coordinape',
  'coordinape.dao',

  // ── Stablecoins / RWA ─────────────────────────────────────────────────────
  'paxos',
  'pax',
  'busd',
  'tusd',
  'gusd',
  'lusd',
  'susd',
  'ageur',
  'eurc',
  'euroe',
  'steur',
  'goldfinch',
  'credix',
  'centrifuge',
  'maple',
  'truefi',
  'trufi',
  'clearpool',
  'ribbon',

  // ── Analytics / Data ──────────────────────────────────────────────────────
  'dune',
  'dunanalytics',
  'dune.analytics',
  'nansen',
  'chainalysis',
  'elliptic',
  'messari',
  'debank',
  'de.bank',
  'zerionapp',
  'zapper',
  'defi.llama',
  'defillama',
  'dexscreener',
  'dex.screener',
  'coingecko',
  'coinmarketcap',
  'glassnode',
  'kaiko',
  'coinmetrics',

  // ── Security / Audit ─────────────────────────────────────────────────────
  'openzeppelin.audit',
  'trail.of.bits',
  'trailofbits',
  'consensys.diligence',
  'peckshield',
  'certik',
  'hacken',
  'quantstamp',
  'slowmist',
  'immunefi',

  // ── Celebrities / Influencers (web3-adjacent) ─────────────────────────────
  'elonmusk',
  'elon.musk',
  'musk.elon',
  'mark.cuban',
  'markcuban',
  'cuban.mark',
  'snoop',
  'snoopdog',
  'snoop.dog',
  'paris',
  'parishilton',
  'paris.hilton',
  'beeple',
  'pak',
  'xcopy',
  'fewocious',
  'gmoney',
  'g.money',
  'punk6529',
  'punk.6529',
  'cobie',
  'crypto.cobain',
  'cryptocobain',
  'banklessben',
  'ryansean',
  'ryan.sean',
  'sean.ryan',
  'defidad',
  'defi.dad',
  'camila',
  'russo',
  'camilarusso',

  // ── Salva specific reserved ───────────────────────────────────────────────
  'salva',
  'salvadao',
  'salva.dao',
  'salvanexus',
  'salva.nexus',
  // "cboi",
  "charlesokoronkwo",
  "charles.okoronkwo",
  "okoronkwo.charles",
];

// Build a Set for O(1) lookup
const RESERVED_NAMES_SET = new Set(RESERVED_NAMES_LIST.map((n) => n.toLowerCase()));

/**
 * Checks whether a pure name (no namespace) is reserved.
 * Also checks both halves of a dot-split name.
 * @param {string} name - the pure name, e.g. "vitalik" or "charles.okoronkwo"
 * @returns {boolean}
 */
function isReservedName(name) {
  if (!name || typeof name !== 'string') return false;
  const lower = name.toLowerCase().trim();

  // Check the whole name first
  if (RESERVED_NAMES_SET.has(lower)) return true;

  // If it has a period, check both halves independently
  if (lower.includes('.')) {
    const parts = lower.split('.');
    for (const part of parts) {
      if (part && RESERVED_NAMES_SET.has(part)) return true;
    }
    // Also check the reversed compound: "a.b" -> check "b.a"
    if (parts.length === 2) {
      const reversed = `${parts[1]}.${parts[0]}`;
      if (RESERVED_NAMES_SET.has(reversed)) return true;
    }
  }

  return false;
}

module.exports = { isReservedName, RESERVED_NAMES_SET, RESERVED_NAMES_LIST };
