// Salva-Digital-Tech/packages/backend/src/models/ReservedNames.js
// This model is NOT a Mongoose schema — it is a hardcoded lookup set.
// All names are stored lowercase. The lookup is O(1) via Set.

const RESERVED_NAMES_LIST = [
  // ── Ethereum / Core Web3 ─────────────────────────────────────────────────
  "vitalik",
  "buterin",
  "vitalikbuterin",
  "vitalik_buterin",
  "buterin_vitalik",
  "gavin",
  "wood",
  "gavinwood",
  "gavin_wood",
  "wood_gavin",
  "silvio",
  "micali",
  "silviomicali",
  "silvio_micali",
  "micali_silvio",
  "hoskinson",
  "charleshoskinson",
  "charles_hoskinson",
  "hoskinson_charles",
  "anatoly",
  "yakovenko",
  "anatolyyakovenko",
  "anatoly_yakovenko",
  "yakovenko_anatoly",
  "ryan",
  "selkis",
  "ryanselkis",
  "ryan_selkis",
  "selkis_ryan",
  "balaji",
  "srinivasan",
  "balajisrinivasan",
  "balaji_srinivasan",
  "srinivasan_balaji",
  "nick",
  "szabo",
  "nickszabo",
  "nick_szabo",
  "szabo_nick",
  "adam",
  "back",
  "adamback",
  "adam_back",
  "back_adam",
  "hal",
  "finney",
  "halfinney",
  "hal_finney",
  "finney_hal",
  "satoshi",
  "nakamoto",
  "satoshinakamoto",
  "satoshi_nakamoto",
  "nakamoto_satoshi",
  "roger",
  "ver",
  "rogerver",
  "roger_ver",
  "ver_roger",
  "brian",
  "armstrong",
  "brianarmstrong",
  "brian_armstrong",
  "armstrong_brian",
  "sam",
  "bankman",
  "samfried",
  "sambankmanfried",
  "sam_bankman",
  "bankman_sam",
  "justin",
  "sun",
  "justinsun",
  "justin_sun",
  "sun_justin",
  "changpeng",
  "zhao",
  "cz",
  "changpengzhao",
  "changpeng_zhao",
  "zhao_changpeng",
  "do",
  "kwon",
  "dokwon",
  "do_kwon",
  "kwon_do",
  "stani",
  "kulechov",
  "stanikulechov",
  "stani_kulechov",
  "kulechov_stani",
  "andre",
  "cronje",
  "andrecronje",
  "andre_cronje",
  "cronje_andre",
  "hayden",
  "adams",
  "haydenbadams",
  "hayden_adams",
  "adams_hayden",
  "kain",
  "warwick",
  "kainwarwick",
  "kain_warwick",
  "warwick_kain",
  "robert",
  "leshner",
  "robertleshner",
  "robert_leshner",
  "leshner_robert",
  "rune",
  "christensen",
  "runechristensen",
  "rune_christensen",
  "christensen_rune",

  // ── Major Protocols & Projects ────────────────────────────────────────────
  "ethereum",
  "eth",
  "bitcoin",
  "btc",
  "solana",
  "sol",
  "polygon",
  "matic",
  "avalanche",
  "avax",
  "bnb",
  "binance",
  "cardano",
  "ada",
  "polkadot",
  "dot",
  "cosmos",
  "atom",
  "chainlink",
  "link",
  "uniswap",
  "uni",
  "aave",
  "compound",
  "maker",
  "dai",
  "usdc",
  "usdt",
  "tether",
  "curve",
  "sushiswap",
  "sushi",
  "yearn",
  "yfi",
  "synthetix",
  "snx",
  "balancer",
  "1inch",
  "paraswap",
  "dydx",
  "gmx",
  "gains",
  "perp",
  "drift",
  "opensea",
  "blur",
  "rarible",
  "foundation",
  "zora",
  "optimism",
  "op",
  "arbitrum",
  "arb",
  "zksync",
  "starknet",
  "base",
  "linea",
  "scroll",
  "mantle",
  "aptos",
  "apt",
  "sui",
  "near",
  "algorand",
  "algo",
  "tezos",
  "xtz",
  "filecoin",
  "fil",
  "arweave",
  "ar",
  "helium",
  "hnt",
  "render",
  "rndr",
  "fetch",
  "fet",

  // ── Wallets ───────────────────────────────────────────────────────────────
  "metamask",
  "meta_mask",
  "mask_meta",
  "trustwallet",
  "trust_wallet",
  "wallet_trust",
  "coinbase",
  "coinbasewallet",
  "coinbase_wallet",
  "wallet_coinbase",
  "rainbow",
  "rainbowwallet",
  "rainbow_wallet",
  "phantom",
  "phantomwallet",
  "phantom_wallet",
  "ledger",
  "ledgerwallet",
  "ledger_wallet",
  "trezor",
  "trezorwallet",
  "trezor_wallet",
  "exodus",
  "exoduswallet",
  "exodus_wallet",
  "atomic",
  "atomicwallet",
  "atomic_wallet",
  "argent",
  "argentwallet",
  "argent_wallet",
  "zerion",
  "zerionwallet",
  "zerion_wallet",
  "safe",
  "gnosis",
  "gnosissafe",
  "gnosis_safe",
  "safe_gnosis",
  "rabby",
  "rabbywallet",
  "rabby_wallet",
  "frame",
  "framewallet",
  "frame_wallet",
  "backpack",
  "backpackwallet",
  "backpack_wallet",
  "okx",
  "okxwallet",
  "okx_wallet",
  "bybit",
  "bybitwallet",
  "bybit_wallet",
  "kraken",
  "krakenwallet",
  "kraken_wallet",
  "binancewallet",
  "binance_wallet",

  // ── Exchanges ─────────────────────────────────────────────────────────────
  "ftx",
  "gemini",
  "kucoin",
  "huobi",
  "gateio",
  "bitfinex",
  "bitstamp",
  "poloniex",
  "bithumb",
  "bitget",
  "mexc",
  "lbank",
  "bitmart",
  "probit",

  // ── DeFi Infrastructure ───────────────────────────────────────────────────
  "lido",
  "lidofinance",
  "lido_finance",
  "finance_lido",
  "rocketpool",
  "rocket_pool",
  "pool_rocket",
  "frax",
  "fraxfinance",
  "frax_finance",
  "convex",
  "convexfinance",
  "convex_finance",
  "pendle",
  "pendlefinance",
  "pendle_finance",
  "eigenlayer",
  "eigen_layer",
  "layer_eigen",
  "ether",
  "etherfi",
  "ether_fi",
  "fi_ether",
  "jito",
  "jitonetwork",
  "jito_network",
  "marinade",
  "marinadefinance",
  "marinade_finance",
  "olympus",
  "ohm",
  "klima",
  "klimadao",
  "klima_dao",
  "sperax",
  "bluechip",
  "reserve",
  "reflexer",

  // ── NFT / Gaming ──────────────────────────────────────────────────────────
  "bayc",
  "mayc",
  "cryptopunks",
  "crypto_punks",
  "azuki",
  "doodles",
  "moonbirds",
  "clonex",
  "sandbox",
  "decentraland",
  "axie",
  "axieinfinity",
  "axie_infinity",
  "stepn",
  "sorare",
  "gods",
  "godenchained",
  "gods_unchained",
  "illuvium",
  "gala",
  "immutable",
  "imx",
  "enjin",
  "enj",
  "superrare",
  "knownorigin",

  // ── Infrastructure / Dev ──────────────────────────────────────────────────
  "infura",
  "alchemy",
  "morales",
  "quicknode",
  "ankr",
  "the_graph",
  "thegraph",
  "graph",
  "subgraph",
  "hardhat",
  "foundry",
  "truffle",
  "brownie",
  "openzeppelin",
  "open_zeppelin",
  "zeppelin",
  "ethers",
  "web3js",
  "web3_js",
  "viem",
  "wagmi",
  "walletconnect",
  "wallet_connect",
  "connect_wallet",
  "wormhole",
  "layerzero",
  "layer_zero",
  "axelar",
  "multichain",
  "multi_chain",
  "across",
  "hop",
  "stargate",
  "stargateprotocol",
  "stargate_protocol",
  "socket",
  "celer",
  "celernetwork",
  "celer_network",

  // ── DAOs / Governance ─────────────────────────────────────────────────────
  "uniswap_dao",
  "aave_dao",
  "compound_dao",
  "maker_dao",
  "makerdao",
  "gitcoin",
  "git_coin",
  "bankless",
  "bank_less",
  "banklessdao",
  "bankless_dao",
  "pleasrdao",
  "pleasr_dao",
  "constitutionaldao",
  "constitution_dao",
  "flamincome",
  "indexcoop",
  "index_coop",
  "rabbithole",
  "rabbit_hole",
  "layer3",
  "layer_3",
  "coordinape",
  "coordinape_dao",

  // ── Stablecoins / RWA ─────────────────────────────────────────────────────
  "paxos",
  "pax",
  "busd",
  "tusd",
  "gusd",
  "lusd",
  "susd",
  "ageur",
  "eurc",
  "euroe",
  "steur",
  "goldfinch",
  "credix",
  "centrifuge",
  "maple",
  "truefi",
  "trufi",
  "clearpool",
  "ribbon",

  // ── Analytics / Data ──────────────────────────────────────────────────────
  "dune",
  "dunanalytics",
  "dune_analytics",
  "nansen",
  "chainalysis",
  "elliptic",
  "messari",
  "debank",
  "de_bank",
  "zerionapp",
  "zapper",
  "defi_llama",
  "defillama",
  "dexscreener",
  "dex_screener",
  "coingecko",
  "coinmarketcap",
  "glassnode",
  "kaiko",
  "coinmetrics",

  // ── Security / Audit ─────────────────────────────────────────────────────
  "openzeppelin_audit",
  "trail_of_bits",
  "trailofbits",
  "consensys_diligence",
  "peckshield",
  "certik",
  "hacken",
  "quantstamp",
  "slowmist",
  "immunefi",

  // ── Celebrities / Influencers (web3-adjacent) ─────────────────────────────
  "elonmusk",
  "elon_musk",
  "musk_elon",
  "mark_cuban",
  "markcuban",
  "cuban_mark",
  "snoop",
  "snoopdog",
  "snoop_dog",
  "paris",
  "parishilton",
  "paris_hilton",
  "beeple",
  "pak",
  "xcopy",
  "fewocious",
  "gmoney",
  "g_money",
  "punk6529",
  "punk_6529",
  "cobie",
  "crypto_cobain",
  "cryptocobain",
  "banklessben",
  "ryansean",
  "ryan_sean",
  "sean_ryan",
  "defidad",
  "defi_dad",
  "camila",
  "russo",
  "camilarusso",

  // ── Salva specific reserved ───────────────────────────────────────────────
  "salva",
  "salvadao",
  "salva_dao",
  "salvanexus",
  "salva_nexus",
  // "cboi",
  // "charlesokoronkwo",
  // "charles_okoronkwo",
  // "okoronkwo_charles",
  "admin",
  "support",
  "help",
  "official",
  "team",
  "treasury",
  "governance",
  "multisig",
  "multi_sig",
  "registry",
  "registrar",
  "validator",
  "guardian",
  "guardian_salva",
  "null",
  "undefined",
  "root",
  "system",
  "operator",

  // ── Common squats to block ────────────────────────────────────────────────
  "test",
  "demo",
  "example",
  "sample",
  "temp",
  "temporary",
  "anonymous",
  "anon",
  "user",
  "wallet",
  "account",
  "profile",
  "nobody",
  "somebody",
  "everyone",
  "anyone",
];

// Build a Set for O(1) lookup
const RESERVED_NAMES_SET = new Set(
  RESERVED_NAMES_LIST.map((n) => n.toLowerCase()),
);

/**
 * Checks whether a pure name (no namespace) is reserved.
 * Also checks both halves of an underscore-split name.
 * @param {string} name - the pure name, e.g. "vitalik" or "charles_okoronkwo"
 * @returns {boolean}
 */
function isReservedName(name) {
  if (!name || typeof name !== "string") return false;
  const lower = name.toLowerCase().trim();

  // Check the whole name first
  if (RESERVED_NAMES_SET.has(lower)) return true;

  // If it has an underscore, check both halves independently
  if (lower.includes("_")) {
    const parts = lower.split("_");
    for (const part of parts) {
      if (part && RESERVED_NAMES_SET.has(part)) return true;
    }
    // Also check the reversed compound: "a_b" -> check "b_a"
    if (parts.length === 2) {
      const reversed = `${parts[1]}_${parts[0]}`;
      if (RESERVED_NAMES_SET.has(reversed)) return true;
    }
  }

  return false;
}

module.exports = { isReservedName, RESERVED_NAMES_SET, RESERVED_NAMES_LIST };
